# Generated by Django 5.0.6 on 2024-06-12 15:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('progress_tracker', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='characterquestprogress',
            name='progress',
        ),
        migrations.RemoveField(
            model_name='quest',
            name='steps',
        ),
        migrations.AddField(
            model_name='quest',
            name='game',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='progress_tracker.game'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='QuestStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('name', models.CharField(max_length=100)),
                ('order', models.IntegerField()),
                ('quest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='progress_tracker.quest')),
            ],
        ),
        migrations.CreateModel(
            name='CharacterQuestStepProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('completed', models.BooleanField(default=False)),
                ('character', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='progress_tracker.character')),
                ('quest_step', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='progress_tracker.queststep')),
            ],
            options={
                'unique_together': {('character', 'quest_step')},
            },
        ),
    ]
